# Generated by Django 5.2 on 2025-04-21 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('bijoux', 'Bijoux'), ('textile', 'Textile')], max_length=10)),
                ('image', models.ImageField(upload_to='product_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Bijoux',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polytechnicien.product')),
                ('material', models.CharField(max_length=255)),
            ],
            bases=('polytechnicien.product',),
        ),
        migrations.CreateModel(
            name='Textile',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='polytechnicien.product')),
                ('fabric_type', models.CharField(max_length=255)),
            ],
            bases=('polytechnicien.product',),
        ),
    ]
